# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

steps:
- script: echo Hello, world!
          ipconfig
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
- task: Application security testing@2022
  inputs:
    projectName: 'NodeGoat'
    enableProxy: false
    enableSastScan: true
    CheckmarxService: 'SAST'
    preset: 'High and Medium and Low'
    incScan: false
    forceScan: true
    enableDependencyScan: false

