# This workflow is to automate Checkmarx SAST scans.  It runs on a push to the main branch.
#
# The following GitHub Secrets must be first defined:
#   - CHECKMARX_URL
#   - CHECKMARX_USER
#   - CHECKMARX_PASSWORD
#   - CHECKMARX_CLIENT_SECRET
#
# The following variables must be inserted below:
#   - <ProjectName>
#
# Update the 'team' field to reflect the team name used in Checkmarx.
#
# For full documentation, including a list of all inputs, please refer to the README https://github.com/checkmarx-ts/checkmarx-cxflow-github-action
##TESTING CHANGES


name: Checkmarx Security Scan
on:
  push:
    branches:
      - main
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: CX SAST
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Checkmarx CxFlow Action SAST
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.5 #Github Action version
      with:
        project: NodeGoat # <-- Insert Checkmarx SAST Project Name
        team: ${{ secrets.CHECKMARX_TEAMS }}
        checkmarx_url: ${{ secrets.CHECKMARX_URL }} # To be stored in GitHub Secrets.
        checkmarx_username: ${{ secrets.CHECKMARX_USER }} # To be stored in GitHub Secrets.
        checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }} # To be stored in GitHub Secrets.
        checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }} # To be stored in GitHub Secrets.

        #sca_api_url: https://api.scacheckmarx.com
        #sca_app_url: https://sca.scacheckmarx.com
        #sca_access_control_url: https://platform.checkmarx.net
        #sca_tenant: ${{ secrets.SCATENANT }}  # <-- Insert Checkmarx CxSCA Tenant
        #sca_username: ${{ secrets.CHECKMARX_SCA_USERNAME }} # To be stored in GitHub Secrets.
        #sca_password: ${{ secrets.CHECKMARX_SCA_PASSWORD }} # To be stored in GitHub Secrets.

        break_build: false
        scanners: sast
        bug_tracker: JIRA
        
        JIRA_URL: ${{ secrets.JIRA_URL }} 
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        JIRA_PROJECT: NOD
        JIRA_ISSUE_TYPE: BUG
        JIRA_OPEN_TRANSITION: In Progress
        JIRA_CLOSE_TRANSITION: Done 
        JIRA_OPEN_STATUS: To Do, In Progress
        JIRA_CLOSED_STATUS: Done
   
        params: --namespace=${{ github.repository_owner }} \
                --repo-name=${{ github.event.repository.name }} \
                --branch=${{ github.ref }} \
                --app=NodeGoat
                --cx-flow.filterSeverity \
                --cx-flow.filterCategory \  
                --checkmarx.disable-clubbing=true \
                --jira.issue-prefix="CX-SAST"
                
    #- name: Upload SAST SARIF file
    #  uses: github/codeql-action/upload-sarif@v1
    #  with:
    #    sarif_file: cx.sarif
        
    - name: Checkmarx CxFlow Action SCA
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.5 #Github Action version
      with:
        project: NodeGoat # <-- Insert Checkmarx SAST Project Name
        #team: ${{ secrets.CHECKMARX_TEAMS }}
        #checkmarx_url: ${{ secrets.CHECKMARX_URL }} # To be stored in GitHub Secrets.
        #checkmarx_username: ${{ secrets.CHECKMARX_USER }} # To be stored in GitHub Secrets.
        #checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }} # To be stored in GitHub Secrets.
        #checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }} # To be stored in GitHub Secrets.

        sca_api_url: https://api.scacheckmarx.com
        sca_app_url: https://sca.scacheckmarx.com
        sca_access_control_url: https://platform.checkmarx.net
        sca_tenant: ${{ secrets.SCATENANT }}  # <-- Insert Checkmarx CxSCA Tenant
        sca_username: ${{ secrets.CHECKMARX_SCA_USERNAME }} # To be stored in GitHub Secrets.
        sca_password: ${{ secrets.CHECKMARX_SCA_PASSWORD }} # To be stored in GitHub Secrets.

        break_build: false
        scanners: SCA
        bug_tracker: JIRA
        
        JIRA_URL: ${{ secrets.JIRA_URL }} 
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        JIRA_PROJECT: NOD
        JIRA_ISSUE_TYPE: BUG
        JIRA_OPEN_TRANSITION: In Progress
        JIRA_CLOSE_TRANSITION: Done 
        JIRA_OPEN_STATUS: To Do, In Progress
        JIRA_CLOSED_STATUS: Done
        
        params: --namespace=${{ github.repository_owner }} \
                --repo-name=${{ github.event.repository.name }} \
                --branch=${{ github.ref }} \
                --app=NodeGoat
                --cx-flow.filterSeverity \
                --cx-flow.filterCategory \  
                --checkmarx.disable-clubbing=true \
                --jira.issue-prefix="CX-SCA"
                
    #- name: Upload SCA SARIF file
    #  uses: github/codeql-action/upload-sarif@v1
    #  with:
    #    sarif_file: cx.sarif
